# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 22]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout Git Source
      uses: actions/checkout@v5

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install --no-package-lock

    - name: Lint
      run: npm run lint

    - name: Unit tests
      run: npm run test-local
      env:
        HTTP_PROXY: ''
        HTTPS_PROXY: ''
        ALL_PROXY: ''
        NO_PROXY: ''

    - name: Coverage
      if: runner.os == 'Linux' && matrix.node-version == 20
      run: npm run cov
      env:
        HTTP_PROXY: ''
        HTTPS_PROXY: ''
        ALL_PROXY: ''
        NO_PROXY: ''

    - name: Code Coverage
      if: runner.os == 'Linux' && matrix.node-version == 20 && secrets.CODECOV_TOKEN != ''
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
